### ISSUE TITLE
Rake task `gen_investigate_csv` failed

### ISSUE THREAD

**Issue by jonpage** [UHERO/udaman#39]
```
YXR_R@JP.A: 1971-01-01: 241.8652, 241.85351668988292 diff:0.01099999999999568
JP_STKNS@yahoo.com
IP@meti.go.jp
2011@hiwi.org
ca_cpi@bea.gov
rake aborted!
ActiveRecord::SubclassNotFound: The single-table inheritance mechanism failed to locate the subclass: '["application/vnd.ms-excel"]'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite DsdLogEntry.inheritance_column to use another column for that information.
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/inheritance.rb:186:in `rescue in find_sti_class'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/inheritance.rb:180:in `find_sti_class'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/inheritance.rb:169:in `discriminate_class_for_record'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/persistence.rb:67:in `instantiate'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/querying.rb:50:in `block (2 levels) in find_by_sql'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/result.rb:51:in `block in each'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/result.rb:51:in `each'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/result.rb:51:in `each'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/querying.rb:50:in `map'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/querying.rb:50:in `block in find_by_sql'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/querying.rb:49:in `find_by_sql'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/statement_cache.rb:107:in `execute'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:445:in `get_records'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:449:in `find_target'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:392:in `load_target'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/associations/collection_proxy.rb:45:in `load_target'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/associations/collection_proxy.rb:908:in `=='
/Users/uhero/Documents/nudaman/lib/tasks/INVESTIGATE.rake:93:in `block (3 levels) in <top (required)>'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/Users/uhero/Documents/nudaman/lib/tasks/INVESTIGATE.rake:91:in `block (2 levels) in <top (required)>'
/Users/uhero/Documents/nudaman/lib/tasks/INVESTIGATE.rake:89:in `block in <top (required)>'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in `exec'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/bin/bundle:23:in `load'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/bin/bundle:23:in `<main>'
NameError: wrong constant name ["application/vnd.ms-excel"]
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:261:in `const_get'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `each'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `inject'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `constantize'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:566:in `get'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:597:in `constantize'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/inheritance.rb:181:in `find_sti_class'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/inheritance.rb:169:in `discriminate_class_for_record'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/persistence.rb:67:in `instantiate'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/querying.rb:50:in `block (2 levels) in find_by_sql'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/result.rb:51:in `block in each'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/result.rb:51:in `each'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/result.rb:51:in `each'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/querying.rb:50:in `map'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/querying.rb:50:in `block in find_by_sql'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/querying.rb:49:in `find_by_sql'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/statement_cache.rb:107:in `execute'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:445:in `get_records'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:449:in `find_target'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/associations/collection_association.rb:392:in `load_target'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/associations/collection_proxy.rb:45:in `load_target'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/associations/collection_proxy.rb:908:in `=='
/Users/uhero/Documents/nudaman/lib/tasks/INVESTIGATE.rake:93:in `block (3 levels) in <top (required)>'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/Users/uhero/Documents/nudaman/lib/tasks/INVESTIGATE.rake:91:in `block (2 levels) in <top (required)>'
/Users/uhero/Documents/nudaman/lib/tasks/INVESTIGATE.rake:89:in `block in <top (required)>'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in `exec'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/bin/bundle:23:in `load'
/Users/uhero/.rvm/gems/ruby-2.3.0@rails4.2/bin/bundle:23:in `<main>'
Tasks: TOP => gen_investigate_csv
(See full trace by running task with --trace)
```

**Comment by vcward** [comment]
- [ ] Create replacement for `type` in `dsd_log_entry`.
- [ ] Copy from `type` to new column.
- [ ] Modify, inserts to, and reads from `dsd_log_entry` to use new column.
- [ ] Remove `type` column.
